apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
  - http:
      paths:
      - path: /currency-exchange/
        pathType: Prefix
        backend:
          service:
           name: currency-exchange
           port:
              number: 8000     
      - path:  /currency-conversion/
        pathType: Prefix
        backend:
          service: 
           name: currency-conversion
           port:
              number: 8100
      - path:  /hello-java
        pathType: Prefix
        backend:
          service: 
           name: hello-java
           port:
              number: 8080
      - path:  /hello-java-v1
        pathType: Prefix
        backend:
          service: 
           name: hello-java-v1
           port:
              number: 8080
      - path:  /hello-java-v2
        pathType: Prefix
        backend:
          service: 
           name: hello-java-v2
           port:
              number: 8080